# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKOtYDZcqJI40-Ca_7xo5wq7oDQvRTWo
"""

import pandas as pd

data = {
    'Davlat': ['AQSh', 'Hindiston', 'Braziliya', 'Fransiya', 'Italiya'],
    'Covid_Holatlari': [1000000, 900000, 850000, 700000, 500000]
}


df = pd.DataFrame(data)


print(df)